// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nemesys.Data;

#nullable disable

namespace Nemesys.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240522084208_someReports")]
    partial class someReports
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Nemesys.Models.Report", b =>
                {
                    b.Property<int>("ReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportID"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfReport")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Upvotes")
                        .HasColumnType("int");

                    b.HasKey("ReportID");

                    b.ToTable("Reports");

                    b.HasData(
                        new
                        {
                            ReportID = 1,
                            Content = "Content of Report 1",
                            DateOfReport = new DateTime(2024, 5, 22, 10, 42, 7, 894, DateTimeKind.Local).AddTicks(6895),
                            ImageUrl = "https://example.com/image1.jpg",
                            Title = "Report 1",
                            Upvotes = 5
                        },
                        new
                        {
                            ReportID = 2,
                            Content = "Content of Report 2",
                            DateOfReport = new DateTime(2024, 5, 21, 10, 42, 7, 894, DateTimeKind.Local).AddTicks(6946),
                            ImageUrl = "https://example.com/image2.jpg",
                            Title = "Report 2",
                            Upvotes = 10
                        },
                        new
                        {
                            ReportID = 3,
                            Content = "Content of Report 3",
                            DateOfReport = new DateTime(2024, 5, 20, 10, 42, 7, 894, DateTimeKind.Local).AddTicks(6952),
                            ImageUrl = "https://example.com/image3.jpg",
                            Title = "Report 3",
                            Upvotes = 7
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
